language: scala

sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
  - 2.13.6

jdk:
  - openjdk11


script:
  - sbt clean coverage test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt docker

after_success:
  - bash <(curl -s https://codecov.io/bash)

